name: nanowebserver

services:
  web:
    image: eriksoderblom/alpine-apache-php:latest
    restart: unless-stopped
    volumes:
      - ./www:/htdocs
    networks:
      - tor
    environment:
      - TZ=America/Argentina/Buenos_Aires

  tor:
    build:
      dockerfile_inline: |
        FROM alpine:latest
        RUN apk add --no-cache tor
        COPY tor/torrc /etc/tor/torrc
        COPY tor/hidden_service /var/lib/tor/hidden_service
        RUN adduser -S alpine-tor
        RUN chown -R alpine-tor /var/lib/tor
        RUN chmod -R 700 /var/lib/tor
        USER alpine-tor
        ENTRYPOINT ["/usr/bin/tor", "-f", "/etc/tor/torrc"]
    restart: unless-stopped
    networks:
      - tor

networks:
  tor:
    driver: bridge
