services:
  website:
    build: .
    restart: unless-stopped
    volumes:
      - ./log:/var/log
      - ./www:/var/www
      - ./additional_config:/mnt/additional_config:ro
      - ./letsencrypt:/etc/letsencrypt
    environment:
      - DOMAIN=${DOMAIN-localhost}
      - CERTBOT_ENABLED=${CERTBOT_ENABLED-false}
      - CERTBOT_EMAIL=${CERTBOT_EMAIL-admin@${DOMAIN}}
