user www-data;
worker_processes auto;
pid /run/nginx.pid;

error_log /dev/stdout info;

include /etc/nginx/modules-enabled/*.conf;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    access_log /dev/stdout;

    sendfile on;
    tcp_nopush on;
    gzip on;
    types_hash_max_size 2048;
    client_max_body_size 32m;

    server_tokens off;
    server_name_in_redirect off;

    ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    include /etc/nginx/sites-enabled/*.conf;
}
