; This file runs after the default php.ini-production provided by the official php-fpm image
[PHP]
log_errors = on
display_errors = off

opcache.enable = 1

post_max_size = 32M
upload_max_filesize = 32M
